# Date Created		1 May 2024
# Author				Mike Z
# Email				mzinyoni7@outlook.com
# Website				https://mikeio.web.app
# Status				Looking for a job!
# Description			A Fintech Data Service
# Inspired by			https://freecurrencyapi.com

# docker compose -f "docker-compose.yml" up -d --build
# docker compose -f "docker-compose.yml" down
# docker exec -it containerid /bin/bash
# docker exec -it postgres /bin/bash


services:
  # .env must have POSTGRES_PASSWORD, POSTGRES_DB, POSTGRES_USER
  db:
    image: postgres
    volumes:
      # - ./data/db:/var/lib/postgresql/data
      - ./dockervolume/postgres:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    env_file:
      - .env

  mongodb:
    image: mongo:7.0
    restart: always
    expose:
      - 27017
    ports:
      - 27017:27017 
    volumes:
      - ./dockervolume/mongo:/data/db
    container_name: mongodb

  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - cache
      - db
      - mongodb
    environment:
      - SERVER_ADDRESS=0.0.0.0:8000
      - REDIS_CONNECTION=cache:6379
      - DB_HOST=db
      - MONGO_CONNECTION=mongodb://localhost:27017/?authSource=admin

  cron:
    build:
      context: .
      dockerfile: cron.Dockerfile
    env_file:
      - .env
    depends_on:
      - cache
      - db
    environment:
      - SERVER_ADDRESS=0.0.0.0:8000
      - REDIS_CONNECTION=cache:6379
      - DB_HOST=db

  cache:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    expose:
      - 6379
    ports:
      - "6379:6379"
volumes:
  postgres_volume:
  mongodata_volume:

###Example .env
# BEACON_KEY=You can't see me, my name is Mike Z
# BEACON_BASE_CURRENCY=USD

# SYS_NAME=Go Currencies API
# SECRET_KEY=SUPER_EXRE8!
# ENV=DEV

# POSTGRES_USER=pg
# POSTGRES_PASSWORD=pass
# POSTGRES_DB=crud
# DB_HOST=localhost

# # PG ADMIN Db
# PGADMIN_DEFAULT_EMAIL=mzinyoni7@outlook.com
# PGADMIN_DEFAULT_PASSWORD=password
