# Date Created	1 May 2024
# Author				Mike Z
# Email				  mzinyoni7@outlook.com
# Website				https://mikeio.web.app
# Status				Looking for a job!
# Description		A Fintech Data Service
# Inspired by		https://freecurrencyapi.com

# docker compose -f "docker-compose.yml" up -d --build
# docker compose -f "docker-compose.yml" down
# docker exec -it containerid /bin/bash
# docker exec -it postgres /bin/bash

# PLEASE SEE WHAT THE .env FILE IS SUPPOSED TO LOOK LIKE FROM .env.example
services:
  db:
    image: postgres
    volumes:
      # - ./data/db:/var/lib/postgresql/data
      - ./dockervolume/postgres:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    env_file:
      - .env

  mongodb:
    image: mongo:7.0
    restart: always
    expose:
      - 27017
    ports:
      - 27017:27017 
    volumes:
      - ./dockervolume/mongo:/data/db
    container_name: mongodb

  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - cache
      - db
      - mongodb

  cron:
    build:
      context: .
      dockerfile: cron.Dockerfile
    env_file:
      - .env
    depends_on:
      - cache
      - db
      - mongodb

  cache:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    expose:
      - 6379
    ports:
      - "6379:6379"
volumes:
  postgres_volume:
  mongodata_volume:
